version: "3.8"
services: 
    frontend:
        image: node:14.9-alpine
        volumes: 
            - ./frontend:/var/www/frontend
        working_dir: /var/www/frontend
        command: /bin/sh -c "yarn install && yarn start"
        stdin_open: true
        tty: true
        ports:
            - 3000:3000
            - 35729:35729
    database:
        image: postgres:12.0-alpine
        volumes:
            - database_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=mddocs-user
            - POSTGRES_PASSWORD=mddocs-password
            - POSTGRES_DB=mddocs-database
        ports:
            - 5432:5432
    backend:
        image: node:14.9-alpine
        volumes:
            - ./backend:/var/www/backend
        working_dir: /var/www/backend
        command: /bin/sh -c "npm install && npm run migrate up && npm run dev"
        stdin_open: true
        tty: true
        ports:
            - 3001:3000
        environment:
            - NODE_ENV=development
            - PORT=3000
            - DB_HOST=database
            - DB_PORT=5432
            - DB_DATABASE=mddocs-database
            - DB_USERNAME=mddocs-user
            - DB_PASSWORD=mddocs-password
            - DATABASE_URL=postgres://mddocs-user:mddocs-password@database:5432/mddocs-database
        depends_on:
            - database

volumes:
    database_data: