name: CI/CD proccess

on:
  push:
    branches-ignore: [ develop, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Initialize docker
        run: docker-compose up -d database backend && sleep 5 && docker-compose run backend /bin/sh -c "npm install && npm run migrate"
      - name: Run GraphQL tests
        run: docker-compose up -d backend database && sleep 20 && docker-compose run backend npm run test
  notifier:
    runs-on: ubuntu-latest
    steps:
      - name: send custom message with args
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: >
            ğŸ‘¨ğŸ»â€ğŸ’» User <b>${{ github.actor }}</b> in <u>${{ github.repository }}</u>

            Make <em>${{ github.event_name }}</em> on <u>${{ github.ref }}</u>


            ğŸ“ ${{ github.event.head_commit.message }}


            {{#success build.status}}
            âœ… Build #${{github.run_id}} succeeded.
            {{else}}
            âŒ Build #{{build.number}} failed.
            {{/success}}

            ğŸŒ <a href="https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}">Github Action</a>
